### ISSUE TITLE
Learn about google auth and perhaps switch to yup-oauth2 or gcp_auth

### ISSUE THREAD

**Issue by liufuyang** [liufuyang/bigtable_rs#14]
Perhaps switch the current [goauth](https://github.com/durch/rust-goauth) google auth package to 
https://github.com/ramosbugs/openidconnect-rs as it seems more reliable and perhaps even easier to use?

To Read:
- [ ] https://developers.google.com/identity/protocols/oauth2/openid-connect
- [ ] https://openid.net/connect/

The example:
https://github.com/ramosbugs/openidconnect-rs/blob/main/examples/google.rs

**Comment by dwirya** [comment]
Hi @liufuyang , thanks for open-sourcing this project! Is there progress on this ticket ? I'm happy to look into this.

**Comment by liufuyang** [comment]
@dwirya Hey there, thank you, feel free to do it, I haven't started on this yet. Do you also think it is a good idea to do this change? Feel free to make a PR if you have ideas then we can take a look at it together 🙂

**Comment by dwirya** [comment]
@liufuyang good to know, thanks! Ideally I should be able to:
1. Attach a GCP credential in my container
2. Use `gcloud login` to populate `application_default_credentials.json`
3. In my Rust service, use `read_authorized_user_secret()` in [`yup_oauth2`](https://docs.rs/yup-oauth2/latest/yup_oauth2/) (was going to try this instead) that will read that JSON file. 

This way, I don't have to manage the secret files anymore. The current state in `bigtable_rs` requires storing the key-file locally in the container, which I think is less than ideal from a security POV. It's not a deal-breaker, but certainly can be improved. That's my take on it, I'm also happy to experiment with `openidconnect` to compare the two in terms of ergonomics.

**Comment by liufuyang** [comment]
@dwirya Thank you so much. https://github.com/dermesser/yup-oauth2 looks like a good alternative. I don't know the details between yup-oath2 and openidconnect-rs so feel free to choose what you think makes the best case here.

Can you elaborate a bit more about point 1 above?

For points 2 and 3, I think for the current implementation the workflow can still be similar as firstly you run `gcloud login` then set `GOOGLE_APPLICATION_CREDENTIALS=$HOME/.config/gcloud/application_default_credentials.json` to make it work.

> The current state in bigtable_rs requires storing the key-file locally in the container, which I think is less than ideal from a security POV

Totally agree if we could find a way to not store key json file inside a container, it's just for now I am not sure how do you solve it via things like yup-oauth2.

What we are really lacking is an implementation of [Application Default Credentials](https://google.aip.dev/auth/4110), for example [here](https://github.com/googleapis/google-auth-library-java#application-default-credentials) is a Google's Java implementation.

But looks like yup-oauth2 is already providing this feature, as its readme says:
> Service account flow: Non-interactive authorization of server-to-server communication based on public key cryptography. Used for services like Cloud Pubsub, Cloud Storage, ...

And perhaps this feature is what you want to try out? It would be super nice if you could test this out. Using a key json file with `GOOGLE_APPLICATION_CREDENTIALS` is easy and if we could figure out a way to allow `Service Account` flow works then that would be super awesome :)

**Comment by liufuyang** [comment]
Just to note down some docs about ServiceAccount auth:
- [CloudRun ServiceAccount fetching access token](https://cloud.google.com/run/docs/securing/service-identity#access-tokens)
- [Compute Engine auth directly with access tokens](https://cloud.google.com/run/docs/securing/service-identity#fetching_identity_and_access_tokens_using_the_metadata_server)

**Comment by liufuyang** [comment]
Otherwise, please give a look at https://github.com/hrvolapeter/gcp_auth

Seems to be an even simpler implementation and provides exactly what we need here?

**Comment by dwirya** [comment]
I actually don't have much experience in OAuth too 😅. But I'm sure given enough time to read through the docs I can figure something out.

Regarding my point 1, coming from AWS, when running a container, Fargate (CloudRun equivalent) will inject the credentials into the container via volume mounting. I'm pretty sure a similar flow exists in GCP from skimming through the [docs](https://cloud.google.com/run/docs/securing/service-identity#per-service-identity) here.

I'm not particularly happy with my current solution, which is to embed the key-file in the project and hence, the container itself. I can also do `gcloud login` in the container, but since each key-file can only be downloaded once, I will end up with one key-file per image. Since a key-file is permanent, this may pose security risks if one of the key-files is compromised, because now I don't know which key-file to disable. Therefore, I think embedding it is safer, since if it's compromised, I just need to replace it with a new key-file.

**Comment by dwirya** [comment]
The `gcp_auth` crate looks interesting, although I prefer to use `yup_oauth2` simply because other GCP crates such as [bigquery_storage](https://docs.rs/bigquery-storage/latest/bigquery_storage/) are using it as well, so it looks more reliable.

If it's all good to you, I'll fork the current `main` branch and try out Application Default Credentials (ADC) using `yup_oauth2` and a service account attached to the container. Will let you know soon 😁.

**Comment by liufuyang** [comment]
I see. [bigquery_storage](https://docs.rs/bigquery-storage/latest/bigquery_storage/) seems not being maintained well or? I think we can use whatever we feel is simple here. Yes feel free to create a PR and if you don't have time for looking deeper into gcp_auth, I might be able to give it a try if I have time.

One more thing is, I still didn't understand your statement:
> I'm not particularly happy with my current solution, which is to embed the key-file in the project and hence, the container itself.

The current version of bigtable_rs does support config `GOOGLE_APPLICATION_CREDENTIALS` so you can in your container set a volume mounting that contains a credential JSON (so do not embed any key-file in the docker image, and you only do it once with a single key), then in your container environment param setting you set `GOOGLE_APPLICATION_CREDENTIALS=/path/to/your/container/secret/volume/mount/key.json`

Wouldn't this solve your problem?

What I don't see is what extra it brings to you by using `yup_oauth2` here as we already have `goauth` used here (but we need more code in this repo to make it really work). For now I don't see how will `yup_oauth2` help you better than the current bigtable_rs impl. (Only benefit for us here is it can probably reduce the line of code here.) Or perhaps I missed something? 🤔 

The doc link you did above is about [service identity](https://cloud.google.com/run/docs/securing/service-identity#per-service-identity) and that is a very different way than mounting key.json (either backing in the image or using k8s/cloudrun secret volume mounting). Perhaps that is what you want - do not use any json key and do not set any `GOOGLE_APPLICATION_CREDENTIALS`? Then for sure we will be in need of something like `yup_oauth2` or `gcp_auth` 😄

**Comment by liufuyang** [comment]
@dwirya I got some time yesterday and here https://github.com/liufuyang/bigtable_rs/pull/27 is my proposal and I think gcp_auth is a cleaner solution + simpler API? 

You can take a look at the [last commit](https://github.com/liufuyang/bigtable_rs/pull/27/commits/b6bc65c3b3d2dfdc4b0a6cde501ee50f0b57bbca) showing the part of start using gcp_auth.

Let me know if you like this approach. Otherwise, if you want to try with yup_oauth2, you can checkout from my branch and try switch gcp_auth to yup_oauth2. We can take a look at whether it feels better. What do you think?

**Comment by dwirya** [comment]
Hi @liufuyang , sorry for the late reply as I've been busy with work. Currently we've decided to do the volume mounting approach similar to your proposal, and I think it's probably more straightforward than using ADC in my opinion. Therefore I don't really see the benefit of my initial approach anymore.

But seeing that you're using `gcp_auth`, I think it looks pretty good. Since I won't be using ADC until I hit a roadblock, I don't really have any opinions regarding the change. If there's anything else you'd like me to investigate, you can let me know :)

**Comment by liufuyang** [comment]
Sounds great then, I will try release a new version soon with this updates as I think it will be more efficient than the current implemention. Feel free to try it when I release a new version and if having any problems just let me know I can try fix it as soon as possible 👍

**Comment by liufuyang** [comment]
@dwirya I have version `0.2.1` released, if you want, give it a try and let me know if you encounter any issues. I will close this issue for now. Thanks again for taking initiative to help here :)
